export const setIcon = {
    0: "icon-sunny.webp",
    1: "icon-sunny.webp",
    2: "icon-partly-cloudy.webp",
    3: "icon-overcast.webp",
    45: "icon-fog.webp",
    48: "icon-fog.webp",
    51: "icon-drizzle.webp",
    53: "icon-drizzle.webp",
    55: "icon-drizzle.webp",
    61: "icon-rain.webp",
    63: "icon-rain.webp",
    65: "icon-rain.webp",
    71: "icon-snow.webp",
    73: "icon-snow.webp",
    75: "icon-snow.webp",
    80: "icon-rain.webp",
    81: "icon-rain.webp",
    82: "icon-rain.webp",
    95: "icon-storm.webp",
    96: "icon-storm.webp",
    99: "icon-storm.webp"
};
